import { useEffect, useState } from "react";
import { fetchOpportunities, IntelligenceApiError, type Opportunity } from "./intelligenceApi";

export function OpportunitiesPage({ apiBaseUrl, embedded = false }: { readonly apiBaseUrl: string; readonly embedded?: boolean }) {
  const [items, setItems] = useState<readonly Opportunity[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { const controller = new AbortController(); void fetchOpportunities(fetch, apiBaseUrl, controller.signal).then(setItems).catch((reason: unknown) => { if (!controller.signal.aborted) setError(reason instanceof IntelligenceApiError ? reason.message : "Opportunities unavailable."); }); return () => controller.abort(); }, [apiBaseUrl]);
  if (error) return <section className={embedded ? "embedded-page" : "intelligence-page"}><div className="state-panel error-panel" role="alert"><h2>Opportunities unavailable</h2><p>{error}</p></div></section>;
  if (!items) return <section className={embedded ? "embedded-page" : "intelligence-page"}><div className="state-banner" role="status">Loading cited opportunities…</div></section>;
  return <section className={embedded ? "embedded-page" : "intelligence-page"}>{!embedded && <header className="page-intro"><p className="eyebrow">Evidence required</p><h2>Opportunities</h2></header>}
    {items.length === 0 ? <div className="state-panel"><h3>No evidence-backed opportunities yet</h3><p>Commercial rank alone is not enough. Publish a cited daily hypothesis or verified deep dive first.</p></div> : <div className="opportunity-grid">{items.map((item, index) => <article className="opportunity-card" key={`${item.work_id}-${item.kind}-${index}`}><header><span className={`action-label ${item.kind === "commercial" ? "amber" : ""}`}>{item.label.replaceAll("_", " ")}</span><strong>{Math.round(item.confidence * 100)}% confidence</strong></header><h2>{item.headline}</h2><p>{item.detail}</p><dl>{item.target_customer && <div><dt>Target customer</dt><dd>{item.target_customer}</dd></div>}{item.painful_workflow && <div><dt>Painful workflow</dt><dd>{item.painful_workflow}</dd></div>}{item.proposed_offer && <div><dt>Proposed offer</dt><dd>{item.proposed_offer}</dd></div>}{item.provisional_pricing && <div><dt>Provisional pricing</dt><dd>{item.provisional_pricing}</dd></div>}{item.validation_experiment && <div><dt>Validation experiment</dt><dd>{item.validation_experiment}</dd></div>}{item.india_market_relevance && <div><dt>India relevance</dt><dd>{item.india_market_relevance}</dd></div>}<div><dt>Evidence</dt><dd>{item.evidence_ids.length} cited spans</dd></div>{item.risks.length > 0 && <div><dt>Risks</dt><dd>{item.risks.join(" · ")}</dd></div>}</dl><a className="source-paper" href={`#discover/${encodeURIComponent(item.work_id)}`}>Open supporting research →</a></article>)}</div>}
  </section>;
}
